### ISSUE TITLE
groupkind -> groupversionresource backup table for geneva actions

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#701]
currently k8s geneva actions walk /api and /apis on the api server, which increases chances of failure if api server is flaky.  Store a backup table mapping groupkind -> groupversionresource for common gks and use this if the api walk fails

**Comment by m1kola** [comment]
I think this is related to https://github.com/Azure/ARO-RP/issues/691

**Comment by m1kola** [comment]
I'll try to put it in other words:

* We need to cache discovery data for `client-go`
* We still want to do discovery for each Geneva action call (so we get the latest state)
* But if discovery fails - we want to fallback to using cache. The cache is our plan B and in the ideal scenario will never be used

@jim-minter do I understand this correctly?

The good news is that `client-go` already has [`discovery.CachedDiscoveryInterface`](https://pkg.go.dev/k8s.io/client-go@v0.16.10/discovery?tab=doc#CachedDiscoveryInterface) and there are two implementations of this interface:

* [`k8s.io/client-go/discovery/cached/memory`](https://pkg.go.dev/k8s.io/client-go@v0.16.10/discovery/cached/memory?tab=doc)
* [`k8s.io/client-go/discovery/cached/disk`](https://pkg.go.dev/k8s.io/client-go@v0.16.10/discovery/cached/disk?tab=doc)

The bad news is that we can't use these implementations, because:

* We run multiple instances of RP on multiple VMs, so memory and disk cache will not work for us: each instance will have own local cache
* It is going to be tricky to use these implementations with multiple clusters
* Disk implementation looks into cache first and makes the API call when there is no cache or it is expired. Not what we want.

So I guess we are looking into adding own implementation of `discovery.CachedDiscoveryInterface` which will be storing cache in the DB or storage account so we can use that cache on different RP instances.

@jim-minter are we trying to solve flakes similar to https://github.com/Azure/ARO-RP/issues/691 or is there something else? It feels like caching and invalidating discovery is like shooting a cannon at sparrows. Maybe retries with N minutes deadline will be enough for this issue?

**Comment by jim-minter** [comment]
@m1kola I was thinking of a single hard-coded table for fallback use that gave a GK->GVR mapping that would be likely to work for the kinds we're interested in on the clusters that we have.  e.g. "Pod -> v1/pods".
Obviously the table wouldn't work for customers CRDs, but it doesn't really matter.
There might be a utility which could populate the table at development time from a test cluster.

Yes, this is to fix #691.
